const BUTTON_TYPES = {
  TAB: "TAB",
  SHIFT: "SHIFT",
  DEFAULT: "DEFAULT",
  ENTER: "ENTER",
  BACKSPACE: "BACKSPACE",
  CAPSLOCK: "CAPSLOCK",
  ESC: "ESC",
  DELETE: "DELETE",
  PAGEUP: "PAGEUP",
  PAGEDOWN: "PAGEDOWN",
  SPACE: "SPACE",
  ALT: "ALT",
};

export default BUTTON_TYPES;
