const BUTTON_TYPES = {
  TAB: "TAB",
  SHIFT: "SHIFT",
  DEFAULT: "DEFAULT",
  ENTER: "ENTER",
  BACKSPACE: "BACKSPACE",
  CAPSLOCK: "CAPSLOCK",
  ESC: "ESC",
  DELETE: "DELETE",
};

export default BUTTON_TYPES;
