const BUTTON_TYPES = {
  TAB: "TAB",
  SHIFT: "SHIFT",
  DEFAULT: "DEFAULT",
  ENTER: "ENTER",
  BACKSPACE: "BACKSPACE",
  CAPSLOCK: "CAPSLOCK",
  ESC: "ESC",
  DELETE: "DELETE",
  PAGEUP: "PAGEUP",
  PAGEDOWN: "PAGEDOWN",
  SPACE: "SPACE",
  ALT: "ALT",
  COPY: "COPY",
  INSERT: "INSERT",
  END: "END",
  START: "START",
};

export default BUTTON_TYPES;
